sudo rm -rf /etc/nomad.d/;
sudo rm -rf /etc/consul.d/;
sudo rm -rf /etc/vault.d/;
sudo rm /usr/local/bin/consul;
sudo rm /usr/local/bin/nomad;
sudo rm /usr/local/bin/vault;
sudo rm -rf /opt/consul;
sudo rm -rf /opt/nomad;
sudo rm -rf /opt/vault;
sudo systemctl stop nomad.service consul.service vault.service;
sudo systemctl disable nomad.service consul.service vault.service;
systemctl daemon-reload;
